# Task (https://taskfile.dev) - use: task migrate | task makemigrations -- "message"
version: "3"

vars:
  ALEMBIC: pipenv run python -m alembic -c alembic.ini

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  api:
    desc: Start the API
    cmds:
      - docker compose up -d api

  api-stop:
    desc: Stop the API
    cmds:
      - docker compose stop api

  migrate:
    desc: Apply migrations to the database
    cmds:
      - "{{.ALEMBIC}} upgrade head"

  makemigrations:
    desc: "Generate migration from models (use: task makemigrations -- 'your message')"
    vars:
      MSG: "{{or .CLI_ARGS \"auto\"}}"
    cmds:
      - '{{.ALEMBIC}} revision --autogenerate -m "{{.MSG}}"'

  check:
    desc: Run ruff check (lint)
    cmds:
      - pipenv run ruff check .

  format:
    desc: Format code with ruff (indent 2)
    cmds:
      - pipenv run ruff format .

  chromedriver:
    desc: Download ChromeDriver via Docker (Linux binary at project root)
    cmds:
      - docker compose run --rm download-chromedriver

  extraction:
    desc: Run extraction
    cmds:
      - PYTHONPATH=. pipenv run python src/etl/extraction.py
