FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir pipenv

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy --dev --ignore-pipfile

CMD ["python", "-m", "src.download_chromedriver", "--force"]
